import re
import json
from typing import Any, Optional

FORMATTER_SYSTEM_PROMPT = """
You are a structural salvage and formatting agent. Your job is to rescue and format classical Arabic diacritized verses that were produced by another model but suffer from formatting issues (e.g. malformed JSON, missing verse_ids, incorrect key names, or partial structures).

You are given:
1. The original list of expected verses (with their exact `verse_id`, `sadr`, and `ajuz`).
2. The raw, malformed, or partial text outputted by the diacritizer model.
3. A description of the formatting error.

Your strict instructions:
1. Do NOT re-diacritize the verses from scratch. Keep the exact diacritics that were generated by the diacritizer model for each word.
2. Align the generated diacritized text from the raw output to the correct `verse_id`s from the expected list.
   - Use index order, word matching, or any hints to ensure every expected `verse_id` is matched with its corresponding diacritized text.
   - If the diacritizer completely missed a verse, use the original (undiacritized) text for that verse to ensure the output list has the exact same length and verse_ids as the input, but flag it or do your best to salvage whatever is available.
3. Ensure that the letters (stripped of diacritics) for each verse match the expected verse's letters EXACTLY. You are forbidden from changing any letters (الحروف) — only format and align the diacritics.
4. Output EXACTLY a valid JSON array wrapped in a ```json code block, with no conversational preamble, and no explanations:
```json
[
  {"verse_id": "...", "sadr": "...", "ajuz": "..."},
  ...
]
```
"""

def strip_diacritics(text: str) -> str:
    """Strip Arabic diacritics (Tashkeel)."""
    return re.sub(r"[\u064b-\u0652\u0670]", "", text)

def clean_and_normalize(text: str) -> str:
    """Normalize text for alignment comparisons."""
    stripped = strip_diacritics(text)
    return re.sub(r"\s+", "", stripped)

def heuristic_salvage(parsed: Any, expected_verses: list[dict]) -> Optional[dict[str, dict]]:
    """Attempt to deterministically align parsed items to expected_verses."""
    if not isinstance(parsed, list):
        return None

    # If length matches exactly, we can assign IDs by index order
    if len(parsed) == len(expected_verses):
        salvaged = {}
        for i, item in enumerate(parsed):
            expected_id = expected_verses[i]["verse_id"]
            # Fall back to expected text if parsed keys are missing
            sadr = item.get("sadr", expected_verses[i]["sadr"])
            ajuz = item.get("ajuz", expected_verses[i].get("ajuz", ""))
            salvaged[expected_id] = {"sadr": sadr, "ajuz": ajuz}
        return salvaged

    # Otherwise, try matching by text similarity
    expected_normalized = {
        clean_and_normalize(v["sadr"] + v.get("ajuz", "")): v["verse_id"]
        for v in expected_verses
    }

    salvaged = {}
    matched_ids = set()

    for item in parsed:
        if not isinstance(item, dict):
            continue
        sadr = item.get("sadr", "")
        ajuz = item.get("ajuz", "")
        norm = clean_and_normalize(sadr + ajuz)

        # Look for exact or close matches
        best_match_id = None
        if norm in expected_normalized:
            best_match_id = expected_normalized[norm]
        else:
            # Check substring/closeness
            for exp_norm, vid in expected_normalized.items():
                if vid in matched_ids:
                    continue
                if norm and (norm in exp_norm or exp_norm in norm):
                    best_match_id = vid
                    break

        if best_match_id:
            salvaged[best_match_id] = {"sadr": sadr, "ajuz": ajuz}
            matched_ids.add(best_match_id)

    # Fill in any missing verses with their original undiacritized text to avoid crashes
    for v in expected_verses:
        vid = v["verse_id"]
        if vid not in salvaged:
            salvaged[vid] = {"sadr": v["sadr"], "ajuz": v.get("ajuz", "")}

    return salvaged

def call_salvage_agent(
    model,
    raw_output: str,
    expected_verses: list[dict],
    error_message: str,
) -> dict[str, dict]:
    """Invoke the salvage LLM agent to restructure and format raw text."""
    from langchain_core.messages import SystemMessage, HumanMessage

    expected_payload = json.dumps(expected_verses, ensure_ascii=False, indent=2)
    user_content = (
        f"Original Expected Verses:\n{expected_payload}\n\n"
        f"Raw Diacritizer Output:\n{raw_output}\n\n"
        f"Detected Formatting Error:\n{error_message}\n\n"
        f"Please salvage, align, and format this output into a valid JSON array."
    )

    messages = [
        SystemMessage(content=FORMATTER_SYSTEM_PROMPT),
        HumanMessage(content=user_content),
    ]

    ai_msg = model.invoke(messages)
    
    # Import _extract_json dynamically to avoid circular dependencies
    from langgraph_pipeline import _extract_json
    try:
        parsed_list = _extract_json(ai_msg.content)
        # Apply deterministic heuristics to the LLM's formatted output as well
        salvaged = heuristic_salvage(parsed_list, expected_verses)
        if salvaged:
            return salvaged
    except Exception as e:
        # If even LLM salvage failed, fall back to returning original verses as last resort
        pass

    # Safe fallback: return expected verses as is rather than crashing
    return {v["verse_id"]: {"sadr": v["sadr"], "ajuz": v.get("ajuz", "")} for v in expected_verses}
